#! /bin/sh

sxhkd &

bspc monitor DVI-I-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          55
bspc config borderless_monocle true
bspc config split_ratio          0.52
bspc config gapless_monocle      true

xrandr --auto --output HDMI-1 --mode 1920x1080 --right-of DVI-I-1 
setxkbmap pl
feh --bg-center ~/.config/wallpaper/wallpaper.jpg
xrdb ~/.Xresources
picom --config ~/.config/picom/picom.conf
