#! /bin/sh

sxhkd &

bspc monitor DVI-I-1 -d I II III IV V
bspc monitor HDMI-1 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          0
bspc config borderless_monocle true
bspc config split_ratio          0.52
bspc config gapless_monocle      true
bspc config border_width 0

bspc config presel_feedback_color "#12222d"

bspc config -m HDMI-1 left_padding 38
bspc config -m HDMI-1 right_padding 38
bspc config -m HDMI-1 top_padding 23
bspc config -m HDMI-1 bottom_padding 23

bspc rule -a URxvt state=floating

cd ~/.config/scripts/
./excludeShadowFromTiledWindows.sh &

xrandr --auto --output HDMI-1 --mode 1920x1080 --right-of DVI-I-1 
setxkbmap pl
feh --bg-tile ~/.config/wallpaper/wallpaper.jpg
xrdb ~/.Xresources
polybar example &
bspc config -m DVI-I-1 top_padding 27
picom --config ~/.config/picom/picom.conf &
./welcome.sh &
